export default {
  colors: {
    primary: "#181030",
    primaryLight: "#E3DAFF",
    secondary: "#ED8839",
    secondary_light: "#FBE7D7",
    success: "#449666",
    white: "#FFFFFF",
    background: "#FFFFFF",
    backgroundDark: "#272627",
    black: "#010104",
    gray: "#6E6C6F",
    lightGray: "#ECE8ED",
    veryLightGray: "#F8F8F8",
    error: "#ED4E4E",
  },
  fonts: {
    blackItalic: "SFProDisplayBlackltalic",
    bold: "SFProDisplayBold",
    boldItalic: "SFProDisplayBoldItalic",
    heavy: "SFProDisplayHeavy",
    heavyItalic: "SFProDisplayHeavyltalic",
    light: "SFProDisplayLight",
    lightItalic: "SFProDisplayLightitalic",
    medium: "SFProDisplayMedium",
    mediumItalic: "SFProDisplayMediumItalic",
    regular: "SFProDisplayRegular",
    regularItalic: "SFProDisplayRegularltalic",
    semibold: "SFProDisplaySemibold",
    semiboldItalic: "SFProDisplaySemiboldItalic",
    thin: "SFProDisplayThin",
    thinItalic: "SFProDisplayThinltalic",
    ultralight: "SFProDisplayUltralight",
    ultralightItalic: "SFProDisplayUltralightitalic",
  },
};
